# Generated by Django 6.0.3 on 2026-04-05 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginotp_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
